### ISSUE TITLE
Fixed Nav Bar Issue

### ISSUE THREAD

**Issue by MckinstryJ** [TravisGM92/MckinstryBrosWebDev#9]
When in full screen mode, the sample text is taking up the entire screen. 

There should be a gap between the nav bar and the sample text and the content of the nav bar should only collapse when in mobile view, so we'll have to revisit this fixed nav bar in the future. 

The way it is now, the css code for "nav" is useless.

**Comment by TravisGM92** [comment]
Yeah I saw that too. Thanks for fixing that.
